version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    command: --api.dashboard --api.insecure --providers.docker --providers.docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3030:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.services.dashboard.loadbalancer.server.port=9999

  web:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=HostRegexp(`{host:.*}`)
      - traefik.http.services.web.loadbalancer.server.port=80
      - traefik.http.middlewares.forward-basic-auth.forwardauth.address=http://forward-basic-auth:4013/auth
      - traefik.http.middlewares.forward-basic-auth.forwardauth.authResponseHeaders=X-Auth-User
      - traefik.http.routers.web.middlewares=forward-basic-auth

  forward-basic-auth:
    image: ghcr.io/spuf/forward-basic-auth
    volumes:
      - forward-basic-auth-data:/var/forward-basic-auth

  init-forward-basic-auth:
    image: alpine:3.14
    command:
      - sh
      - -c
      - apk add curl && curl -X PUT 'http://forward-basic-auth:4013/users' --data-raw '{"user":"pass"}' -v
    depends_on:
      - forward-basic-auth

volumes:
  forward-basic-auth-data:
